### ISSUE TITLE
Deploy destroys sessions

### ISSUE THREAD

**Issue by mvegh1** [mvegh1/DiFractal#141]
And they persist in the database too, weird.

**Comment by mvegh1** [comment]
Aha! I think we are NOT using sql server caching!

http://www.binaryintellect.net/articles/c4f46271-c889-44ef-9b78-c062dc3ed3de.aspx

This says to dependency inject IDistributedCache. However, we are using Session to put the cache. Not sure if thats the issue but I will try this and see if it fixes the issue

**Comment by mvegh1** [comment]
The real solution was to specify where the keys for the Sessions will be stored. 

Tested by deploying and observing session was still alive

**Comment by mvegh1** [comment]
MGZero was right, we dont need to restart the dotnet process hosting the site on every deploy (i.e restart supervisor). We just need to deploy the artifacts

**Comment by mvegh1** [comment]
We DO need to restart afterall!

**Comment by MGZero** [comment]
@mvegh1 What are the reasons the restart is needed?

**Comment by mvegh1** [comment]
We observed before that Dll changes werent being picked up until dotnet
process was restarted. I can reference the hangouts chat if you need a
reminder
