### ISSUE TITLE
As a user, I want to be able to add a new workout

### ISSUE THREAD

**Issue by MGZero** [mvegh1/DiFractal#152]
-There should be an add workout button on the main navigation
-The form should be split into a Details and Exercises tab
-The Details tab should have the following fields:
   1. Type - A typeahead (required)
   2. Rating - A bootstrap 10-star rating
   3. Energy - A bootstrap 10-star rating
   4. A number picker for body weight
   5. A comments field

The exercise tab will handled in a follow up story

**Comment by mvegh1** [comment]
Let's add this UX please:

Each WorkoutItemGrouping in the Add Workout form will NOT show any of the
details controls (reps,sets,weight,rpe,comments,time/reps toggle,etc) UNTIL
an exercise is selected for that grouping
