### ISSUE TITLE
As a user, I want to see errors for validaiton

### ISSUE THREAD

**Issue by MGZero** [mvegh1/DiFractal#155]
-On blur, a field should be validated to see if the rules (required fields, business rules, format etc) for the field pass
-On submit, all fields should be revalidated
-If validation does not pass, there should be an inline error displayed for the field
-If validation passes prior to submit, but fails at the server, an error should display telling the user something went wrong with validation

**Comment by mvegh1** [comment]
Validations are wired up 100%. just needs to look pretty ;)
