### ISSUE TITLE
Inquiry: Add 3rd column to Unit Table for UnitType

### ISSUE THREAD

**Issue by mvegh1** [mvegh1/DiFractal#174]
Thinking this could just be a string for simplicity, i,.e Weight, Temperature, etc. I dont think we need a whole other table (UnitType) to act as an enumeration here

Right now, we only have one Unit type (weight), and I don't like how it's just a simple "Metric" or "Imperial"

**Comment by MGZero** [comment]
If we want this to be at the database level and have users pick, then we should use a lookup table and reference it by ID. It'll be more efficient that way and there will be less room for error.

**Comment by mvegh1** [comment]
Well my idea was to give Unit table this structure:
Id: uniqueidentifier
Name: varchar
Type: varchar

Ex: Pounds, Weight
      Kilogram, Weight
      Celsius, Temperature
Etc

Or, do you really think we should do the following:

    Id, Name,UnitTypeId
     Pounds, 1
     Kilogram, 1
     Celsius, 2

**Comment by MGZero** [comment]
Yea, we should do the latter with the UnitTypeId. It guarantees consistency among unit types via referential integrity

**Comment by mvegh1** [comment]
This might be a dumb question, but why do we want to store units in
Workout, not in Portal?

Example, if we specify all Weights should be Pounds, why should that only
affect Workout app?

Or, does this mean I did it wrong originally, by putting it in Workout?

**Comment by mvegh1** [comment]
Weight doesn't really mean anything to Portal itself, but I can see the
argument how it should be a global setting...

**Comment by MGZero** [comment]
It's meaningless to other apps, so it should stay in workout
