### ISSUE TITLE
Feature: Add ability to create Workout Template / Weekly Template

### ISSUE THREAD

**Issue by mvegh1** [mvegh1/DiFractal#178]
Would be really nice to just create templates that could automatically set the Add Workout form up with that template.

Not exactly sure what a nice UI would be to load the template, but the basic structure of a template would be this:

WorkoutTemplate
Id: Guid
Title: string
Exercises: UserExercise[]
Days?: DayOfWeek[] *optional

Additionally, we can also allow the user to enter Sets and Reps as well, but one thing to note here is a user may not always use the same weight per set, so if we prefilled the form with say, Bench Press 3 sets 8 reps, the user may need to change the 3 to a 1 and then proceed. Or. Maybe they did something different instead. 

The Days? Parameter works great for a 7 day week based template. The Add Workout form could check the day of week either 1) when entering the form or 2) when date field changes, and compare against existing templates. Then, we could prompt the user to load the template for that day. 

I would appreciate comprehensive feedback on this feature, @MGZero 

Thanks

**Comment by MGZero** [comment]
I'm a little confused, we're saving the user time from entering inputs by also entering the same inputs?

**Comment by mvegh1** [comment]
What do you mean?

**Comment by mvegh1** [comment]
Template definition:
COMPUTING
a preset format for a document or file, used so that the format does not
have to be recreated each time it is used.

**Comment by MGZero** [comment]
I'm just not sure if I see how this saves the user time, it needs to be fleshed out more

**Comment by mvegh1** [comment]
It's a workout template, I laid the structure of the template out.

It would prepopulate the add workout form when the template is chosen

It would only be valid on new workouts (Id == Empty Guid)

Ui/ux on add workout form is undecided at this point.

Your confusion stems from the problem I laid out with also including
Sets/Reps in the structure, which i only theorized and did not include in
the formal structure i outlined

Clearer with these additional data?

**Comment by MGZero** [comment]
Ok, so this is something that the user can save permanently and reuse later. Got it. I guess the usefulness of it really depends on how consistent your workouts are. If you just kind of wing your workouts, then the only thing it's really doing for you is saving the title - at which point, the time saved is negated by having to load up your list of templates, find the one you want and finally load

**Comment by mvegh1** [comment]
Correct, but a user who just wings it wouldn't use this feature.

All technology comes loaded with stuff users dont use 😁 I dont use 95% of
my androids features

So, I'm thinking Sets/Reps would actually not be too useful (because of my
earlier reasoning), and days of week doesnt help much.

Thoughts/criticism?

**Comment by MGZero** [comment]
Other tech being bloated with unused features is not a reason to also bloat ours. Follow the 80/20 rule. We can implement it, but don't spend an absurd amount of time on it if you think only 20% of users will use it. 

All of that said, I would agree sets/reps wouldn't be useful and would probably be counter intuitive since there's a pretty high chance you'd have to change it anyway. I'm not sure what else would actually be useful here?

**Comment by mvegh1** [comment]
It's useful to me, that's a huge driver for putting it in 😉
