### ISSUE TITLE
Add Rating to WorkoutEntry

### ISSUE THREAD

**Issue by mvegh1** [mvegh1/DiFractal#44]
Let's make this 1 to 5. Perhaps 5 stars for the UI. Optional, integer

**Comment by MGZero** [comment]
https://ng-bootstrap.github.io/#/components/rating/examples

**Comment by mvegh1** [comment]
For the backend, doing this thru EF is pretty simple

Project: Difractal.Workout.Database
There needs to be an app.json or app.config (I think json) that has the connection string to the db, same as Workout.Web project 

The Models folder contains the Entities, need to update the one with the new property (same as the other fields, getter/setter)

Then, open up Package Manager Console (it's under tools at the top I think, maybe under Nuget thereafter)

In the Console make sure Workout.Database is selected

Then run create-migration  "{{SomeDescription}}"

Then run update-database

If you dont feel like doing this I can do it when I come back 😂
